site_name: Project Documentation
theme:
  name: material
  icon:
    logo: fontawesome/brands/github-alt
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - content.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle: 
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

extra:
  socials:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Lech-iyoko
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alechenu-iyoko-b2b0a8233/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

copyright: 
  "&copy; 2023 <a href ='https://github.com/Lech-iyoko' target= '_blank' rel='noopener'>Lech Iyoko</a>"
